version: '3'
services:
  data_lake:
    container_name: data_lake
    restart: always
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    stdin_open: true
    tty: true
    networks:
      - serums
    environment:
      - BC_PATH=http://host.docker.internal:30001

networks:
  serums:
    external: true
